openapi: 3.1.0
info:
  description: Backstory API Specification
  title: SecOps Backstory API
  version: v1
servers:
- url: "https://backstory.googleapis.com/v1"
- url: "https://{region}-backstory.googleapis.com/v1"
  variables:
    region:
      default: europe
      enum:
        - southamerica-east1
        - northamerica-northeast2
        - me-central2
        - me-central1
        - europe
        - europe-west3
        - europe-west2
        - asia-south1
        - europe-west9
        - asia-southeast1
        - australia-southeast1
        - me-west1
        - asia-northeast1
        - europe-west12
        - backstory.googleapis.com
        - europe-west6
paths:
  /tools/cbnParsers:
    get:
      operationId: ListParsers
      responses:
        200:
          description: List of parsers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListParsersResponse"
      tags:
      - cbnParsers
  /tools/cbnParsers/{logType}:
    parameters:
      - name: logType
        in: path
        schema:
          type: string
    get:
      operationId: GetParser
      responses:
        200:
          description: Parser config
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Parser"
      tags:
      - cbnParsers
  /partner/customer/listcustomers:
    get:
      operationId: ListCustomers
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListCustomersResponse"
      tags:
      - customer
  /partner/customer/getcustomer:
    parameters:
      - name: customer_code
        in: query
        required: true
        schema:
          type: string
    get:
      operationId: GetCustomers
      responses:
        200:
          description: Customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
      tags:
      - customer
components:
  schemas:
    Customer:
      type: object
    Parser:
      properties:
        config:
          type: string
        logType:
          type: string
    ListParsersResponse:
      properties:
        cbnParsers:
          items:
            $ref: "#/components/schemas/Parser"
          type: array
    ListCustomersResponse:
      properties:
        customers:
          items:
            $ref: "#/components/schemas/Customer"
          type: array
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/cloud-platform: ""
    http:
      type: http
      scheme: bearer
security:
  - oauth2: []
  - http: [https://www.googleapis.com/auth/cloud-platform]